version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
